# Generated by Django 2.2.1 on 2019-07-09 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('contact', models.CharField(max_length=10)),
                ('salary', models.IntegerField(default=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('p_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.IntegerField()),
                ('entry_date', models.DateField()),
                ('flag', models.BooleanField(default=False)),
                ('ind_cost', models.FloatField(default=0.0)),
                ('empid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='cost.Employee')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='cost.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Project_estimation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(default=0)),
                ('projid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='cost.Project')),
            ],
        ),
    ]
