# Generated by Django 2.2.1 on 2019-07-10 10:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cost', '0002_auto_20190709_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept_work',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='concept_work',
            name='desc',
            field=models.CharField(default=2, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='description',
            field=models.CharField(default=2, max_length=40),
            preserve_default=False,
        ),
    ]
